name: ewallet
description: E-wallet

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.1.0
  circular_reveal_animation: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_font_icons: ^2.2.5

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
  fonts:
    - family: SVN-Gotham
      fonts:
        - asset: assets/fonts/SVN-Gotham Black.otf
        - asset: assets/fonts/SVN-Gotham Bold.otf
        - asset: assets/fonts/SVN-Gotham Italic.otf
        - asset: assets/fonts/SVN-Gotham Regular.otf

    - family: SVN-Days
      fonts:
        - asset: assets/fonts/SVN-Days.otf

